### Checking responses
@localhost = http://localhost:8000/api


POST {{localhost}}/login/
content-type: application/json

{
    "username": "arya@site.com",
    "password": "123456"
}

### Cheking logout
POST http://localhost:8000/api/auth/logout/
Authorization: Token 909bd847d4d616229905b38851432c709cb7315a6be63d38beb3e6fe316746da

### Checking post response
GET {{localhost}}/post/?email=arya@site.com
Authorization: Token 909bd847d4d616229905b38851432c709cb7315a6be63d38beb3e6fe316746da

### Checking comment response
GET {{localhost}}/comment/?post_id=11
Authorization: Token fe604fb1796078dc260508a3c19a0de3aaa9e4c7d5e264433ad04c5519576aab

###Checking retrieve user information
GET {{localhost}}/account/profile/
Authorization: Token 1eccfe6012d54a4ab9cc751766d0a2c0a8817145ea29713fe23c06a3705dbd14