### Checking responses
@localhost = http://localhost:8000/api


POST {{localhost}}/login/
content-type: application/json

{
    "username": "jonksff@gmail.com",
    "password": "maijo132"
}

### Cheking logout
POST http://localhost:8000/api/auth/logout/
Authorization: Token fe604fb1796078dc260508a3c19a0de3aaa9e4c7d5e264433ad04c5519576aab

### Checking post response
GET {{localhost}}/post/
Authorization: Token 95b5a5f93a813ed1676c53a1b9caa7dd46c02a6c3ff61b0c25b2cdc425e93ad5

### Checking comment response
GET {{localhost}}/comment/?post_id=11
Authorization: Token fe604fb1796078dc260508a3c19a0de3aaa9e4c7d5e264433ad04c5519576aab

###Checking retrieve user information
GET {{localhost}}/account/profile/
Authorization: Token 90b2c55d1204ea88305f8c2984319ab667d7f53a7ff420e49429906f335720ee